<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AttendanceDataService\AttendanceDataService.csproj" />
    <ProjectReference Include="..\AttendanceModels\AttendanceModels.csproj" />
  </ItemGroup>

</Project>
